baseURL = 'https://meltita.github.io/'
languageCode = 'en-US'
title = 'Meltita'
theme = "ananke"
featured_image='/images/gohugo-default-sample-hero-image.jpg'
defaultContentLanguage = "lt"

[languages]
  [languages.en]
    title = "Meltita"
    weight = 2
[[languages.en.menu.main]]
name = "Contacts"
url = "/contacts"
weight = 3
[[languages.en.menu.main]]
name = "About"
url = "/about"
weight = 2
[[languages.en.menu.main]]
name = "Request Rate"
url = "/request-rate"
weight = 4
[[languages.en.menu.main]]
name = "Services"
url = "/services"
weight = 5

[languages.lt]
  title = "Meltita"
  weight = 3
[[languages.lt.menu.main]]
name = "Kontaktai"
url = "/contacts"
weight = 3
[[languages.lt.menu.main]]
name = "Apie"
url = "/about"
weight = 2
[[languages.lt.menu.main]]
name = "Užklausos norma"
url = "/request-rate"
weight = 4
[[languages.lt.menu.main]]
name = "Paslaugos"
url = "/services"
weight = 5

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/apple/"
disable_share = true

[params]
  date_format = "2. January 2006"
  recent_posts_number = 8
